The telecom problem

Suppose that you are a telecom company with three services: TV, internet and telephone. Each service have a billing option: billing_1, billing_2 and billing_3. A customer can subscribe to a combination of services, and depending on his choices he will have to be billed in a way. For example: customer A is subscribed to the internet and telephone service. In our database this customer would have 1 in the columns "internet" and "telephone", and he would have 1 in "billing_2" and "billing_3". However, due to technical and/or human error the billing configuration is not 100% accurate resulting in two customers with the same subscription being billed in different ways.

In [131]:
import pandas as pd
import numpy as np
import prince

In [132]:
pd.set_option("display.max_columns", None)

Reading the "train" dataset

In [133]:
df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")
df_train.head()

,MSISDN,CRM_BUSINESS_LINE_ORIG_Mobile,CRM_1519_PACK,CRM_1521_PACK,CRM_1522_PACK,CRM_1523_PACK,CRM_1524_PACK,CRM_1525_PACK,CRM_1526_PACK,CRM_1527_PACK,CRM_1528_PACK,CRM_1529_PACK,CRM_1530_PACK,CRM_1532_PACK,CRM_1533_PACK,CRM_1534_PACK,CRM_1536_PACK,CRM_1537_PACK,CRM_1538_PACK,CRM_1539_PACK,CRM_1540_PACK,CRM_1541_PACK,CRM_1542_PACK,CRM_1543_PACK,CRM_1545_PACK,CRM_1546_PACK,CRM_1547_PACK,CRM_1548_PACK,CRM_1549_PACK,CRM_1550_PACK,CRM_1551_PACK,CRM_1552_PACK,CRM_1553_PACK,CRM_1554_PACK,CRM_1555_PACK,CRM_1556_PACK,CRM_1557_PACK,CRM_1558_PACK,CRM_1559_PACK,CRM_1560_PACK,CRM_1562_PACK,CRM_1563_PACK,CRM_1564_PACK,CRM_1565_PACK,CRM_1566_PACK,CRM_1567_PACK,CRM_1568_PACK,CRM_1569_PACK,CRM_1570_PACK,CRM_1571_PACK,CRM_1573_PACK,CRM_1575_PACK,CRM_1576_PACK,CRM_1577_PACK,CRM_1578_PACK,CRM_1579_PACK,CRM_1581_PACK,CRM_1582_PACK,CRM_1583_PACK,CRM_1584_PACK,CRM_1585_PACK,CRM_1586_PACK,CRM_1587_PACK,CRM_1588_PACK,CRM_1589_PACK,CRM_1590_PACK,CRM_1591_PACK,CRM_1592_PACK,CRM_1593_PACK,CRM_1594_PACK,CRM_1595_PACK,CRM_1596_PACK,CRM_1598_PACK,CRM_1599_PACK,CRM_1601_PACK,CRM_1602_PACK,CRM_1603_PACK,CRM_1604_PACK,CRM_1605_PACK,CRM_1606_PACK,CRM_1608_PACK,CRM_1609_PACK,CRM_1612_PACK,CRM_1613_PACK,CRM_1614_PACK,CRM_1615_PACK,CRM_1616_PACK,CRM_1617_PACK,CRM_1619_PACK,CRM_1623_PACK,CRM_1625_PACK,CRM_1626_PACK,CRM_1627_PACK,CRM_1629_PACK,CRM_1630_PACK,CRM_1631_PACK,CRM_1635_PACK,CRM_1638_PACK,CRM_1639_PACK,CRM_1640_PACK,CRM_1641_PACK,CRM_1642_PACK,CRM_1643_PACK,CRM_1644_PACK,CRM_1645_PACK,CRM_1646_PACK,CRM_1647_PACK,CRM_1648_PACK,CRM_1653_PACK,CRM_1654_PACK,CRM_1658_PACK,CRM_1661_PACK,CRM_1662_PACK,CRM_1664_PACK,CRM_1665_PACK,CRM_1666_PACK,CRM_1668_PACK,CRM_1669_PACK,CRM_1670_PACK,CRM_1671_PACK,CRM_1675_PACK,CRM_1676_PACK,CRM_1678_PACK,CRM_1680_PACK,CRM_1683_PACK,CRM_1689_PACK,CRM_1690_PACK,CRM_1692_PACK,CRM_1702_PACK,CRM_1704_PACK,CRM_1705_PACK,CRM_1708_PACK,CRM_1709_PACK,CRM_1710_PACK,CRM_1715_PACK,CRM_2076_PACK,CRM_2077_PACK,CRM_2078_PACK,CRM_2079_PACK,CRM_2080_PACK,CRM_2081_PACK,CRM_2082_PACK,CRM_2083_PACK,CRM_2084_PACK,CRM_2085_PACK,CRM_2086_PACK,CRM_2087_PACK,CRM_2088_PACK,CRM_2089_PACK,CRM_2090_PACK,CRM_2091_PACK,CRM_2092_PACK,CRM_2093_PACK,CRM_2094_PACK,CRM_2095_PACK,CRM_2096_PACK,CRM_2097_PACK,CRM_2099_PACK,CRM_2100_PACK,CRM_2101_PACK,CRM_2102_PACK,CRM_2103_PACK,CRM_2104_PACK,CRM_2105_PACK,CRM_2106_PACK,CRM_2107_PACK,CRM_2109_PACK,CRM_2111_PACK,CRM_2112_PACK,CRM_2113_PACK,CRM_2114_PACK,CRM_2115_PACK,CRM_2116_PACK,CRM_2117_PACK,CRM_2118_PACK,CRM_2121_PACK,CRM_2123_PACK,CRM_2126_PACK,CRM_2127_PACK,CRM_2128_PACK,CRM_2129_PACK,CRM_2130_PACK,CRM_2132_PACK,CRM_2134_PACK,CRM_2135_PACK,CRM_2137_PACK,CRM_2138_PACK,CRM_2139_PACK,CRM_2140_PACK,CRM_SUBSCRIBER_TYPE_ORIG_0,CRM_SUBSCRIBER_TYPE_ORIG_Postpaid,CRM_SUBSCRIBER_TYPE_ORIG_Prepaid,CRM_SUBSCRIBER_STATUS_ORIG_0,CRM_SUBSCRIBER_STATUS_ORIG_Active,CRM_SUBSCRIBER_STATUS_ORIG_Barring,CRM_SUBSCRIBER_STATUS_ORIG_Block_1_Way,CRM_SUBSCRIBER_STATUS_ORIG_Block_2_Way,CRM_SUBSCRIBER_STATUS_ORIG_Deactive,CRM_SUBSCRIBER_STATUS_ORIG_Idle,CRM_SUBSCRIBER_STATUS_ORIG_Pre_Active,CRM_SUBSCRIBER_STATUS_ORIG_Pre_Deactivated,CRM_SUBSCRIBER_STATUS_ORIG_Pre_Expired,CRM_SUBSCRIBER_STATUS_ORIG_Suspend,CRM_2141_PACK,CRM_2142_PACK,CRM_2143_PACK,CRM_2146_PACK,CRM_2147_PACK,CRM_2148_PACK,CRM_2149_PACK,CRM_2153_PACK,CRM_2154_PACK,CRM_2155_PACK,CRM_2161_PACK,CRM_1531_PACK,CRM_1561_PACK,CRM_1597_PACK,CRM_1600_PACK,CRM_1607_PACK,CRM_1610_PACK,CRM_1611_PACK,CRM_1618_PACK,CRM_1620_PACK,CRM_1621_PACK,CRM_1622_PACK,CRM_1624_PACK,CRM_1633_PACK,CRM_1636_PACK,CRM_1637_PACK,CRM_1649_PACK,CRM_1650_PACK,CRM_1651_PACK,CRM_1652_PACK,CRM_1655_PACK,CRM_1656_PACK,CRM_1657_PACK,CRM_1660_PACK,CRM_1663_PACK,CRM_1667_PACK,CRM_1672_PACK,CRM_1673_PACK,CRM_1674_PACK,CRM_1677_PACK,CRM_1679_PACK,CRM_1682_PACK,CRM_1684_PACK,CRM_1685_PACK,CRM_1686_PACK,CRM_1687_PACK,CRM_1688_PACK,CRM_1691_PACK,CRM_1693_PACK,CRM_1694_PACK,CRM_1695_PACK,CRM_1696_PACK,CRM_1697_PACK,CRM_1698_PACK,CRM_1699_PACK,CRM_1700_PACK,CRM_1701_PACK,CRM_1706_PACK,CRM_1712_PACK,CRM_1714_PACK,CRM_1717_PACK,CRM_1718_PACK,CRM_1719_PACK,CRM_1720_PACK,CRM_1721_PACK,CRM_1722_PACK,CRM_1723_PACK,CRM_1724_PACK,CRM_1725_PACK,CRM_1726_PACK,CRM_1727_PACK,CRM_1730_PACK,CRM_1732_PACK,CRM_1734_PACK,CRM_1735_PACK,CRM_1737_PACK,CRM_1738_PACK,CRM_1739_PACK,CRM_1740_PACK,CRM_1741_PACK,CRM_1742_PACK,CRM_1743_PACK,CRM_1744_PACK,CRM_1745_PACK,CRM_1746_PACK,CRM_1748_PACK,CRM_1749_PACK,CRM_1751_PACK,CRM_1752_PACK,CRM_1753_PACK,CRM_1754_PACK,CRM_1755_PACK,CRM_1758_PACK,CRM_1759_PACK,CRM_1760_PACK,CRM_1761_PACK,CRM_1762_PACK,CRM_1763_PACK,CRM_1765_PACK,CRM_1767_PACK,CRM_1769_PACK,CRM_1770_PACK,CRM_1772_PACK,CRM_1773_PACK,CRM_1775_PACK,CRM_1776_PACK,CRM_1777_PACK,CRM_1778_PACK,CRM_1779_PACK,CRM_1780_PACK,CRM_1781_PACK,CRM_1783_PACK,CRM_1784_PACK,CRM_1785_PACK,CRM_1786_PACK,CRM_1790_PACK,CRM_1791_PACK,CRM_1794_PACK,CRM_1797_PACK,CRM_1798_PACK,CRM_1799_PACK,CRM_1803_PACK,CRM_1804_PACK,CRM_1805_PACK,CRM_1806_PACK,CRM_1807_PACK,CRM_1808_PACK,CRM_1809_PACK,CRM_1811_PACK,CRM_1812_PACK,CRM_1813_PACK,CRM_1815_PACK,CRM_1816_PACK,CRM_1817_PACK,CRM_1818_PACK,CRM_1820_PACK,CRM_1824_PACK,CRM_1825_PACK,CRM_1826_PACK,CRM_1827_PACK,CRM_1828_PACK,CRM_1832_PACK,CRM_1833_PACK,CRM_1836_PACK,CRM_1842_PACK,CRM_1843_PACK,CRM_1844_PACK,CRM_1845_PACK,CRM_1848_PACK,CRM_1849_PACK,CRM_1851_PACK,CRM_1865_PACK,CRM_1874_PACK,CRM_1875_PACK,CRM_1876_PACK,CRM_1877_PACK,CRM_1878_PACK,CRM_1881_PACK,CRM_2098_PACK,CRM_2108_PACK,CRM_2110_PACK,CRM_2119_PACK,CRM_2120_PACK,CRM_2122_PACK,CRM_2124_PACK,CRM_2125_PACK,CRM_2133_PACK,CRM_2136_PACK,CRM_2144_PACK,CRM_2145_PACK,CRM_2150_PACK,CRM_2151_PACK,CRM_2152_PACK,CRM_2156_PACK,CRM_2157_PACK,CRM_2158_PACK,CRM_2159_PACK,CRM_2160_PACK,CRM_2163_PACK,CRM_2165_PACK,CRM_2166_PACK,CRM_2167_PACK,CRM_2168_PACK,CRM_2169_PACK,CRM_2170_PACK,CRM_2171_PACK,CRM_2173_PACK,CRM_2174_PACK,CRM_2175_PACK,CRM_2177_PACK,CRM_2178_PACK,CRM_2179_PACK,CRM_2180_PACK,CRM_2182_PACK,CRM_2184_PACK,CRM_2185_PACK,CRM_2186_PACK,CRM_2190_PACK,CRM_2192_PACK,CRM_2193_PACK,CRM_2195_PACK,CRM_2197_PACK,CRM_2201_PACK,CRM_2205_PACK,CRM_2212_PACK,CRM_2219_PACK,CRM_2220_PACK,CRM_1634_PACK,CRM_1659_PACK,CRM_1703_PACK,CRM_1707_PACK,CRM_1711_PACK,CRM_1713_PACK,CRM_1716_PACK,CRM_1728_PACK,CRM_1729_PACK,CRM_1731_PACK,CRM_1733_PACK,CRM_1736_PACK,CRM_1747_PACK,CRM_1750_PACK,CRM_1756_PACK,CRM_1757_PACK,CRM_1764_PACK,CRM_1766_PACK,CRM_1768_PACK,CRM_1771_PACK,CRM_1774_PACK,CRM_1782_PACK,CRM_1787_PACK,CRM_1788_PACK,CRM_1789_PACK,CRM_1792_PACK,CRM_1793_PACK,CRM_1795_PACK,CRM_1796_PACK,CRM_1800_PACK,CRM_1801_PACK,CRM_1802_PACK,CRM_1810_PACK,CRM_1814_PACK,CRM_1819_PACK,CRM_1821_PACK,CRM_1822_PACK,CRM_1823_PACK,CRM_1829_PACK,CRM_1830_PACK,CRM_1834_PACK,CRM_1835_PACK,CRM_1840_PACK,CRM_1841_PACK,CRM_1846_PACK,CRM_1847_PACK,CRM_1850_PACK,CRM_1852_PACK,CRM_1853_PACK,CRM_1854_PACK,CRM_1855_PACK,CRM_1856_PACK,CRM_1857_PACK,CRM_1858_PACK,CRM_1859_PACK,CRM_1860_PACK,CRM_1861_PACK,CRM_1862_PACK,CRM_1863_PACK,CRM_1864_PACK,CRM_1866_PACK,CRM_1867_PACK,CRM_1868_PACK,CRM_1869_PACK,CRM_1870_PACK,CRM_1871_PACK,CRM_1873_PACK,CRM_1879_PACK,CRM_1880_PACK,CRM_1883_PACK,CRM_1884_PACK,CRM_1885_PACK,CRM_1886_PACK,CRM_1887_PACK,CRM_1888_PACK,CRM_1889_PACK,CRM_1890_PACK,CRM_1892_PACK,CRM_1893_PACK,CRM_1894_PACK,CRM_1895_PACK,CRM_1896_PACK,CRM_1899_PACK,CRM_1900_PACK,CRM_1901_PACK,CRM_1902_PACK,CRM_1903_PACK,CRM_1905_PACK,CRM_1906_PACK,CRM_1907_PACK,CRM_1908_PACK,CRM_1909_PACK,CRM_1911_PACK,CRM_1912_PACK,CRM_1917_PACK,CRM_1926_PACK,CRM_1933_PACK,CRM_1941_PACK,CRM_1943_PACK,CRM_1944_PACK,CRM_1946_PACK,CRM_1949_PACK,CRM_1950_PACK,CRM_1952_PACK,CRM_1953_PACK,CRM_1954_PACK,CRM_1956_PACK,CRM_1961_PACK,CRM_1962_PACK,CRM_1963_PACK,CRM_1964_PACK,CRM_1966_PACK,CRM_2061_PACK,CRM_2063_PACK,CRM_2066_PACK,CRM_2068_PACK,CRM_2069_PACK,CRM_2070_PACK,CRM_2071_PACK,CRM_2072_PACK,CRM_2073_PACK,CRM_2074_PACK,CRM_2075_PACK,CRM_2131_PACK,CRM_2176_PACK,CRM_2181_PACK,CRM_2183_PACK,CRM_2187_PACK,CRM_2188_PACK,CRM_2191_PACK,CRM_2194_PACK,CRM_2196_PACK,CRM_2198_PACK,CRM_2199_PACK,CRM_2200_PACK,CRM_2203_PACK,CRM_2204_PACK,CRM_2206_PACK,CRM_2207_PACK,CRM_2208_PACK,CRM_2210_PACK,CRM_2213_PACK,CRM_2214_PACK,CRM_2216_PACK,CRM_2218_PACK,CRM_2221_PACK,CRM_2222_PACK,CRM_2223_PACK,CRM_2224_PACK,CRM_2225_PACK,CRM_2226_PACK,CRM_2228_PACK,CRM_2229_PACK,CRM_2230_PACK,CRM_2231_PACK,CRM_2234_PACK,CRM_2235_PACK,CRM_2236_PACK,CRM_2237_PACK,CRM_2238_PACK,CRM_2239_PACK,CRM_2240_PACK,CRM_2241_PACK,CRM_2242_PACK,CRM_2243_PACK,CRM_2244_PACK,CRM_2245_PACK,CRM_2246_PACK,CRM_2247_PACK,CRM_2248_PACK,CRM_2249_PACK,CRM_2250_PACK,CRM_2251_PACK,CRM_2253_PACK,CRM_2254_PACK,CRM_2256_PACK,CRM_2257_PACK,CRM_2259_PACK,CRM_2262_PACK,CRM_2263_PACK,CRM_2265_PACK,CRM_2267_PACK,CRM_2271_PACK,CRM_2276_PACK,CRM_2283_PACK,CRM_2287_PACK,CRM_2290_PACK,CRM_2296_PACK,CRM_2299_PACK,CRM_2301_PACK,CRM_2302_PACK,CRM_2307_PACK,CRM_2309_PACK,CRM_2317_PACK,CRM_1632_PACK,CRM_1831_PACK,CRM_1839_PACK,CRM_1872_PACK,CRM_1882_PACK,CRM_1891_PACK,CRM_1897_PACK,CRM_1904_PACK,CRM_1910_PACK,CRM_1930_PACK,CRM_1931_PACK,CRM_1932_PACK,CRM_1951_PACK,CRM_1959_PACK,CRM_1968_PACK,CRM_1969_PACK,CRM_2062_PACK,CRM_2064_PACK,CRM_2065_PACK,CRM_2067_PACK,CRM_2164_PACK,CRM_2189_PACK,CRM_2209_PACK,CRM_2211_PACK,CRM_2215_PACK,CRM_2227_PACK,CRM_2232_PACK,CRM_2233_PACK,CRM_2252_PACK,CRM_2255_PACK,CRM_2258_PACK,CRM_2266_PACK,CRM_2268_PACK,CRM_2269_PACK,CRM_2270_PACK,CRM_2272_PACK,CRM_2273_PACK,CRM_2274_PACK,CRM_2275_PACK,CRM_2277_PACK,CRM_2278_PACK,CRM_2279_PACK,CRM_2280_PACK,CRM_2281_PACK,CRM_2282_PACK,CRM_2284_PACK,CRM_2285_PACK,CRM_2286_PACK,CRM_2288_PACK,CRM_2289_PACK,CRM_2291_PACK,CRM_2292_PACK,CRM_2293_PACK,CRM_2294_PACK,CRM_2297_PACK,CRM_2298_PACK,CRM_2300_PACK,CRM_2303_PACK,CRM_2304_PACK,CRM_2305_PACK,CRM_2306_PACK,CRM_2308_PACK,CRM_2311_PACK,CRM_2312_PACK,CRM_2313_PACK,CRM_2314_PACK,CRM_2315_PACK,CRM_2316_PACK,CRM_2319_PACK,CRM_2320_PACK,CRM_2321_PACK,CRM_2322_PACK,CRM_2323_PACK,CRM_2324_PACK,CRM_2325_PACK,CRM_2326_PACK,CRM_2327_PACK,CRM_2328_PACK,CRM_2329_PACK,CRM_2330_PACK,CRM_2331_PACK,CRM_2332_PACK,CRM_2333_PACK,CRM_2335_PACK,CRM_2336_PACK,CRM_2337_PACK,CRM_2338_PACK,CRM_2339_PACK,CRM_2340_PACK,CRM_2341_PACK,CRM_2342_PACK,CRM_2343_PACK,CRM_2344_PACK,CRM_2345_PACK,CRM_2346_PACK,CRM_2347_PACK,CRM_2348_PACK,CRM_2349_PACK,CRM_2351_PACK,CRM_2352_PACK,CRM_2353_PACK,CRM_2354_PACK,CRM_2355_PACK,CRM_2356_PACK,CRM_2357_PACK,CRM_2358_PACK,CRM_2359_PACK,CRM_2360_PACK,CRM_2361_PACK,CRM_2362_PACK,CRM_2363_PACK,CRM_2364_PACK,CRM_2365_PACK,CRM_2366_PACK,CRM_2367_PACK,CRM_2368_PACK,CRM_2369_PACK,CRM_2370_PACK,CRM_2371_PACK,CRM_2372_PACK,CRM_2373_PACK,CRM_2374_PACK,CRM_2375_PACK,CRM_2376_PACK,CRM_2377_PACK,CRM_2378_PACK,CRM_2379_PACK,CRM_2380_PACK,CRM_2381_PACK,CRM_2382_PACK,CRM_2383_PACK,CRM_2385_PACK,CRM_2387_PACK,CRM_2388_PACK,CRM_2389_PACK,CRM_2391_PACK,CRM_2392_PACK,CRM_2394_PACK,CRM_2395_PACK,CRM_2396_PACK,CRM_2397_PACK,CRM_2398_PACK,BIL_BUSINESS_LINE_ORIG_Mobile,BIL_3737_PACK,BIL_3739_PACK,BIL_3740_PACK,BIL_3741_PACK,BIL_3742_PACK,BIL_3743_PACK,BIL_3744_PACK,BIL_3745_PACK,BIL_3746_PACK,BIL_3748_PACK,BIL_3749_PACK,BIL_3750_PACK,BIL_3751_PACK,BIL_3752_PACK,BIL_3753_PACK,BIL_3754_PACK,BIL_3755_PACK,BIL_3756_PACK,BIL_3757_PACK,BIL_3758_PACK,BIL_3760_PACK,BIL_3761_PACK,BIL_3762_PACK,BIL_3763_PACK,BIL_3764_PACK,BIL_3765_PACK,BIL_3766_PACK,BIL_3767_PACK,BIL_3769_PACK,BIL_3770_PACK,BIL_3771_PACK,BIL_3772_PACK,BIL_3773_PACK,BIL_3774_PACK,BIL_3775_PACK,BIL_3776_PACK,BIL_3777_PACK,BIL_3778_PACK,BIL_3780_PACK,BIL_3781_PACK,BIL_3782_PACK,BIL_3784_PACK,BIL_3785_PACK,BIL_3786_PACK,BIL_3787_PACK,BIL_3788_PACK,BIL_3789_PACK,BIL_3791_PACK,BIL_3792_PACK,BIL_3794_PACK,BIL_3796_PACK,BIL_3797_PACK,BIL_3798_PACK,BIL_3799_PACK,BIL_3801_PACK,BIL_3802_PACK,BIL_3803_PACK,BIL_3804_PACK,BIL_3805_PACK,BIL_3815_PACK,BIL_3817_PACK,BIL_3820_PACK,BIL_3821_PACK,BIL_3822_PACK,BIL_3824_PACK,BIL_3829_PACK,BIL_3831_PACK,BIL_3833_PACK,BIL_3839_PACK,BIL_3841_PACK,BIL_3884_PACK,BIL_3920_PACK,BIL_3921_PACK,BIL_3922_PACK,BIL_3923_PACK,BIL_3924_PACK,BIL_3925_PACK,BIL_3926_PACK,BIL_3927_PACK,BIL_3928_PACK,BIL_3929_PACK,BIL_3930_PACK,BIL_3931_PACK,BIL_3932_PACK,BIL_3933_PACK,BIL_3934_PACK,BIL_3935_PACK,BIL_3936_PACK,BIL_3939_PACK,BIL_3940_PACK,BIL_3941_PACK,BIL_3942_PACK,BIL_3943_PACK,BIL_3944_PACK,BIL_3948_PACK,BIL_3949_PACK,BIL_3950_PACK,BIL_3952_PACK,BIL_3953_PACK,BIL_3954_PACK,BIL_3955_PACK,BIL_3956_PACK,BIL_3957_PACK,BIL_3958_PACK,BIL_3959_PACK,BIL_3960_PACK,BIL_3961_PACK,BIL_3962_PACK,BIL_3963_PACK,BIL_3964_PACK,BIL_3965_PACK,BIL_3966_PACK,BIL_3968_PACK,BIL_3969_PACK,BIL_3971_PACK,BIL_3972_PACK,BIL_3973_PACK,BIL_3974_PACK,BIL_3975_PACK,BIL_3977_PACK,BIL_3979_PACK,BIL_3980_PACK,BIL_3981_PACK,BIL_3983_PACK,BIL_3985_PACK,BIL_3988_PACK,BIL_3989_PACK,BIL_3992_PACK,BIL_3994_PACK,BIL_3995_PACK,BIL_3996_PACK,BIL_3997_PACK,BIL_3998_PACK,BIL_4001_PACK,BIL_4004_PACK,BIL_4005_PACK,BIL_4006_PACK,BIL_4009_PACK,BIL_4012_PACK,BIL_4013_PACK,BIL_4014_PACK,BIL_4015_PACK,BIL_4016_PACK,BIL_4019_PACK,BIL_4020_PACK,BIL_4021_PACK,BIL_4024_PACK,BIL_4025_PACK,BIL_4032_PACK,BIL_4036_PACK,BIL_4037_PACK,BIL_4038_PACK,BIL_4039_PACK,BIL_4040_PACK,BIL_4041_PACK,BIL_4042_PACK,BIL_4043_PACK,BIL_4044_PACK,BIL_4045_PACK,BIL_4046_PACK,BIL_4047_PACK,BIL_4048_PACK,BIL_4050_PACK,BIL_4051_PACK,BIL_4052_PACK,BIL_4054_PACK,BIL_4055_PACK,BIL_4056_PACK,BIL_4060_PACK,BIL_4061_PACK,BIL_4062_PACK,BIL_4063_PACK,BIL_4064_PACK,BIL_4065_PACK,BIL_4066_PACK,BIL_4067_PACK,BIL_4068_PACK,BIL_4071_PACK,BIL_4072_PACK,BIL_4075_PACK,BIL_4076_PACK,BIL_4078_PACK,BIL_4079_PACK,BIL_4082_PACK,BIL_4084_PACK,BIL_4089_PACK,BIL_4097_PACK,BIL_4102_PACK,BIL_4103_PACK,BIL_4105_PACK,BIL_4106_PACK,BIL_4107_PACK,BIL_SUBSCRIBER_STATUS_ORIG_0,BIL_SUBSCRIBER_STATUS_ORIG_Active,BIL_SUBSCRIBER_STATUS_ORIG_Barring,BIL_SUBSCRIBER_STATUS_ORIG_Block_1_Way,BIL_SUBSCRIBER_STATUS_ORIG_Block_2_Way,BIL_SUBSCRIBER_STATUS_ORIG_Idle,BIL_SUBSCRIBER_STATUS_ORIG_Pre_Active,BIL_SUBSCRIBER_STATUS_ORIG_Pre_Deactivated,BIL_SUBSCRIBER_STATUS_ORIG_Pre_Expired,BIL_SUBSCRIBER_STATUS_ORIG_Suspend,BIL_SUBSCRIBER_TYPE_ORIG_0,BIL_SUBSCRIBER_TYPE_ORIG_Postpaid,BIL_SUBSCRIBER_TYPE_ORIG_Prepaid,BIL_4108_PACK,BIL_4111_PACK,BIL_4126_PACK,BIL_4150_PACK,BIL_4171_PACK,BIL_4184_PACK,BIL_3759_PACK,BIL_3779_PACK,BIL_3790_PACK,BIL_3793_PACK,BIL_3795_PACK,BIL_3806_PACK,BIL_3807_PACK,BIL_3808_PACK,BIL_3809_PACK,BIL_3810_PACK,BIL_3811_PACK,BIL_3812_PACK,BIL_3813_PACK,BIL_3816_PACK,BIL_3819_PACK,BIL_3823_PACK,BIL_3825_PACK,BIL_3826_PACK,BIL_3827_PACK,BIL_3828_PACK,BIL_3830_PACK,BIL_3832_PACK,BIL_3834_PACK,BIL_3835_PACK,BIL_3836_PACK,BIL_3837_PACK,BIL_3838_PACK,BIL_3840_PACK,BIL_3842_PACK,BIL_3844_PACK,BIL_3845_PACK,BIL_3846_PACK,BIL_3847_PACK,BIL_3848_PACK,BIL_3849_PACK,BIL_3850_PACK,BIL_3851_PACK,BIL_3854_PACK,BIL_3855_PACK,BIL_3856_PACK,BIL_3858_PACK,BIL_3860_PACK,BIL_3862_PACK,BIL_3863_PACK,BIL_3872_PACK,BIL_3874_PACK,BIL_3877_PACK,BIL_3880_PACK,BIL_3912_PACK,BIL_3919_PACK,BIL_3937_PACK,BIL_3938_PACK,BIL_3947_PACK,BIL_3951_PACK,BIL_3970_PACK,BIL_3976_PACK,BIL_3982_PACK,BIL_3984_PACK,BIL_3986_PACK,BIL_3987_PACK,BIL_3990_PACK,BIL_3991_PACK,BIL_3993_PACK,BIL_3999_PACK,BIL_4000_PACK,BIL_4002_PACK,BIL_4003_PACK,BIL_4008_PACK,BIL_4010_PACK,BIL_4011_PACK,BIL_4017_PACK,BIL_4018_PACK,BIL_4022_PACK,BIL_4023_PACK,BIL_4026_PACK,BIL_4027_PACK,BIL_4028_PACK,BIL_4029_PACK,BIL_4030_PACK,BIL_4031_PACK,BIL_4033_PACK,BIL_4034_PACK,BIL_4035_PACK,BIL_4049_PACK,BIL_4053_PACK,BIL_4058_PACK,BIL_4059_PACK,BIL_4070_PACK,BIL_4073_PACK,BIL_4074_PACK,BIL_4077_PACK,BIL_4081_PACK,BIL_4085_PACK,BIL_4086_PACK,BIL_4087_PACK,BIL_4088_PACK,BIL_4090_PACK,BIL_4091_PACK,BIL_4093_PACK,BIL_4095_PACK,BIL_4098_PACK,BIL_4099_PACK,BIL_4100_PACK,BIL_4101_PACK,BIL_4104_PACK,BIL_4109_PACK,BIL_4110_PACK,BIL_4112_PACK,BIL_4113_PACK,BIL_4114_PACK,BIL_4115_PACK,BIL_4117_PACK,BIL_4118_PACK,BIL_4119_PACK,BIL_4120_PACK,BIL_4122_PACK,BIL_4123_PACK,BIL_4124_PACK,BIL_4125_PACK,BIL_4131_PACK,BIL_4132_PACK,BIL_4135_PACK,BIL_4136_PACK,BIL_4137_PACK,BIL_4139_PACK,BIL_4140_PACK,BIL_4141_PACK,BIL_4142_PACK,BIL_4143_PACK,BIL_4144_PACK,BIL_4145_PACK,BIL_4147_PACK,BIL_4151_PACK,BIL_4152_PACK,BIL_4153_PACK,BIL_4154_PACK,BIL_4155_PACK,BIL_4156_PACK,BIL_4157_PACK,BIL_4160_PACK,BIL_4161_PACK,BIL_4162_PACK,BIL_4163_PACK,BIL_4165_PACK,BIL_4166_PACK,BIL_4167_PACK,BIL_4168_PACK,BIL_4170_PACK,BIL_4172_PACK,BIL_4173_PACK,BIL_4174_PACK,BIL_4175_PACK,BIL_4176_PACK,BIL_4177_PACK,BIL_4178_PACK,BIL_4179_PACK,BIL_4181_PACK,BIL_4182_PACK,BIL_4183_PACK,BIL_4186_PACK,BIL_4187_PACK,BIL_4188_PACK,BIL_4189_PACK,BIL_4191_PACK,BIL_4195_PACK,BIL_4196_PACK,BIL_4197_PACK,BIL_4198_PACK,BIL_4200_PACK,BIL_4201_PACK,BIL_4204_PACK,BIL_4205_PACK,BIL_4207_PACK,BIL_4208_PACK,BIL_4209_PACK,BIL_4210_PACK,BIL_4226_PACK,BIL_4227_PACK,BIL_4234_PACK,BIL_4236_PACK,BIL_4238_PACK,BIL_4240_PACK,BIL_4250_PACK,BIL_4251_PACK,BIL_4253_PACK,BIL_4254_PACK,BIL_4255_PACK,BIL_4262_PACK,BIL_4267_PACK,BIL_4278_PACK,BIL_4285_PACK,BIL_4286_PACK,BIL_4288_PACK,BIL_4307_PACK,BIL_4308_PACK,BIL_4314_PACK,BIL_3783_PACK,BIL_3800_PACK,BIL_3814_PACK,BIL_3818_PACK,BIL_3843_PACK,BIL_3853_PACK,BIL_3859_PACK,BIL_3861_PACK,BIL_3864_PACK,BIL_3865_PACK,BIL_3866_PACK,BIL_3867_PACK,BIL_3868_PACK,BIL_3870_PACK,BIL_3871_PACK,BIL_3873_PACK,BIL_3875_PACK,BIL_3876_PACK,BIL_3878_PACK,BIL_3879_PACK,BIL_3881_PACK,BIL_3882_PACK,BIL_3883_PACK,BIL_3885_PACK,BIL_3886_PACK,BIL_3887_PACK,BIL_3888_PACK,BIL_3889_PACK,BIL_3890_PACK,BIL_3891_PACK,BIL_3892_PACK,BIL_3893_PACK,BIL_3894_PACK,BIL_3895_PACK,BIL_3896_PACK,BIL_3897_PACK,BIL_3900_PACK,BIL_3901_PACK,BIL_3902_PACK,BIL_3905_PACK,BIL_3906_PACK,BIL_3907_PACK,BIL_3909_PACK,BIL_3910_PACK,BIL_3911_PACK,BIL_3913_PACK,BIL_3914_PACK,BIL_3915_PACK,BIL_3917_PACK,BIL_3918_PACK,BIL_3945_PACK,BIL_3946_PACK,BIL_3967_PACK,BIL_3978_PACK,BIL_4007_PACK,BIL_4069_PACK,BIL_4080_PACK,BIL_4083_PACK,BIL_4092_PACK,BIL_4094_PACK,BIL_4096_PACK,BIL_4116_PACK,BIL_4121_PACK,BIL_4127_PACK,BIL_4130_PACK,BIL_4133_PACK,BIL_4134_PACK,BIL_4138_PACK,BIL_4146_PACK,BIL_4149_PACK,BIL_4158_PACK,BIL_4159_PACK,BIL_4164_PACK,BIL_4169_PACK,BIL_4180_PACK,BIL_4192_PACK,BIL_4193_PACK,BIL_4194_PACK,BIL_4199_PACK,BIL_4202_PACK,BIL_4203_PACK,BIL_4206_PACK,BIL_4212_PACK,BIL_4213_PACK,BIL_4214_PACK,BIL_4215_PACK,BIL_4216_PACK,BIL_4217_PACK,BIL_4218_PACK,BIL_4219_PACK,BIL_4220_PACK,BIL_4221_PACK,BIL_4222_PACK,BIL_4223_PACK,BIL_4224_PACK,BIL_4225_PACK,BIL_4228_PACK,BIL_4229_PACK,BIL_4230_PACK,BIL_4231_PACK,BIL_4232_PACK,BIL_4233_PACK,BIL_4235_PACK,BIL_4237_PACK,BIL_4241_PACK,BIL_4242_PACK,BIL_4244_PACK,BIL_4245_PACK,BIL_4246_PACK,BIL_4247_PACK,BIL_4248_PACK,BIL_4249_PACK,BIL_4252_PACK,BIL_4256_PACK,BIL_4257_PACK,BIL_4258_PACK,BIL_4259_PACK,BIL_4260_PACK,BIL_4261_PACK,BIL_4263_PACK,BIL_4268_PACK,BIL_4270_PACK,BIL_4271_PACK,BIL_4272_PACK,BIL_4273_PACK,BIL_4274_PACK,BIL_4275_PACK,BIL_4276_PACK,BIL_4277_PACK,BIL_4279_PACK,BIL_4280_PACK,BIL_4281_PACK,BIL_4282_PACK,BIL_4283_PACK,BIL_4284_PACK,BIL_4289_PACK,BIL_4290_PACK,BIL_4291_PACK,BIL_4292_PACK,BIL_4293_PACK,BIL_4294_PACK,BIL_4297_PACK,BIL_4298_PACK,BIL_4299_PACK,BIL_4301_PACK,BIL_4303_PACK,BIL_4304_PACK,BIL_4305_PACK,BIL_4309_PACK,BIL_4311_PACK,BIL_4312_PACK,BIL_4313_PACK,BIL_4316_PACK,BIL_4317_PACK,BIL_4318_PACK,BIL_4320_PACK,BIL_4323_PACK,BIL_4324_PACK,BIL_4325_PACK,BIL_4326_PACK,BIL_4328_PACK,BIL_4329_PACK,BIL_4330_PACK,BIL_4332_PACK,BIL_4333_PACK,BIL_4336_PACK,BIL_4337_PACK,BIL_4338_PACK,BIL_4339_PACK,BIL_4340_PACK,BIL_4341_PACK,BIL_4342_PACK,BIL_4343_PACK,BIL_4344_PACK,BIL_4346_PACK,BIL_4349_PACK,BIL_4351_PACK,BIL_4353_PACK,BIL_4365_PACK,BIL_4366_PACK,BIL_4370_PACK,BIL_4374_PACK,BIL_4376_PACK,BIL_4387_PACK,BIL_4389_PACK,BIL_4390_PACK,BIL_4394_PACK,BIL_4399_PACK,BIL_4404_PACK,BIL_4405_PACK,BIL_4408_PACK,BIL_4414_PACK,BIL_4416_PACK,BIL_4453_PACK,BIL_3903_PACK,BIL_3904_PACK,BIL_3908_PACK,BIL_3916_PACK,BIL_4128_PACK,BIL_4185_PACK,BIL_4190_PACK,BIL_4211_PACK,BIL_4239_PACK,BIL_4243_PACK,BIL_4264_PACK,BIL_4265_PACK,BIL_4266_PACK,BIL_4287_PACK,BIL_4295_PACK,BIL_4296_PACK,BIL_4300_PACK,BIL_4302_PACK,BIL_4306_PACK,BIL_4315_PACK,BIL_4321_PACK,BIL_4327_PACK,BIL_4334_PACK,BIL_4335_PACK,BIL_4345_PACK,BIL_4347_PACK,BIL_4348_PACK,BIL_4350_PACK,BIL_4354_PACK,BIL_4355_PACK,BIL_4356_PACK,BIL_4357_PACK,BIL_4358_PACK,BIL_4359_PACK,BIL_4360_PACK,BIL_4361_PACK,BIL_4362_PACK,BIL_4363_PAC

Separating our columns in three types: id, input and output

In [134]:
id_col = df_train['MSISDN'].name
crm_cols = [c for c in df_train.columns if not c.startswith("BIL") and c != id_col]
bil_cols = [c for c in df_train.columns if c.startswith("BIL")]

Transforming column type due to memory performance issue

In [135]:
df_train[crm_cols] = df_train[crm_cols].astype(np.uint8)
df_train[bil_cols] = df_train[bil_cols].astype(np.uint8)

Selecting active columns by removing constant ones

In [136]:
active_crm = [c for c in crm_cols if df_train[c].min() != df_train[c].max()]
active_bil = [c for c in bil_cols if df_train[c].min() != df_train[c].max()]

print(f"Active CRM Features retained: {len(active_crm)} / {len(crm_cols)}")
print(f"Active Billing Targets retained: {len(active_bil)} / {len(bil_cols)}")

Active CRM Features retained: 743 / 745
Active Billing Targets retained: 731 / 731

In [137]:
X_active = df_train[active_crm]
Y_active = df_train[active_bil]

In [138]:
dropped_crm = [c for c in crm_cols if c not in active_crm]
print("Removed CRM columns:", dropped_crm)

Removed CRM columns: ['CRM_2396_PACK', 'CRM_2398_PACK']

Saving the cleaned dataset

In [139]:
df_clean = df_train[active_crm + active_bil]

df_clean.to_csv('cleaned_telecom_data.csv', index=False)

In [140]:
# Check for missing values in each column
missing_values = df_clean.isnull().sum()
print(missing_values[missing_values > 0])
print("Total missing values in cleaned dataset:", df_clean.isnull().sum().sum())

Series([], dtype: int64)
Total missing values in cleaned dataset: 0

In [141]:
# Check for fully duplicated rows (same MSISDN or same values across all columns)
duplicate_rows = df_clean.duplicated().sum()
print("Number of fully duplicated rows in cleaned dataset:", duplicate_rows)

Number of fully duplicated rows in cleaned dataset: 119264

In [142]:
df_clean = df_clean.drop_duplicates()

print(f'Original shape: {df_train.shape}')
print(f'Cleaned shape: {df_clean.shape}')

Original shape: (187442, 1477)
Cleaned shape: (68178, 1474)

In [143]:
print("\nTop 3 most common CRM packs (in cleaned data):")
print(df_clean[active_crm].sum().sort_values(ascending=False).head(3))

print("\nTop 3 most common Billing packs (in cleaned data):")
print(df_clean[active_bil].sum().sort_values(ascending=False).head(3))

Top 3 most common CRM packs (in cleaned data):
CRM_BUSINESS_LINE_ORIG_Mobile       67939
CRM_SUBSCRIBER_TYPE_ORIG_Prepaid    55312
CRM_1537_PACK                       48172
dtype: uint64

Top 3 most common Billing packs (in cleaned data):
BIL_BUSINESS_LINE_ORIG_Mobile       67921
BIL_SUBSCRIBER_TYPE_ORIG_Prepaid    55229
BIL_3748_PACK                       48223
dtype: uint64

In [144]:
# Compare CRM combinations: does test have combos never seen in train?
train_combos = set(map(tuple, df_clean[active_crm].values))
test_combos = set(map(tuple, test[active_crm].values))

overlap = train_combos & test_combos

print("Unique CRM combos in train:", len(train_combos))
print("Unique CRM combos in test:", len(test_combos))
print("Test combos also seen in train:", len(overlap))
print("Test combos NEVER seen in train:", len(test_combos - train_combos))

Unique CRM combos in train: 67434
Unique CRM combos in test: 97100
Test combos also seen in train: 6
Test combos NEVER seen in train: 97094

## Key finding: train/test CRM overlap is nearly zero

Only 6 out of 97,100 unique CRM combinations in the test set 
also appear in the training set (99.99% are unseen combinations).

**Implication for Sprint 2 (Modeling):**
This means we cannot rely on exact-match methods, such as 
Nearest Neighbor lookup or Label Powerset classification, since 
these require test customers to closely match combinations seen 
during training.

Instead, we should use a model that learns general rules from 
individual CRM features (e.g., Random Forest or XGBoost, one 
model per Billing column), since this type of model can still 
predict correctly for combinations it has never seen exactly, 
by combining rules learned from smaller pieces of the data.

## Modelling

### Multiple Correspondence Analysis

Creating the MCA model, with the number of parameters same as the number of columns in the model, since the Bénzecri correction spreads the variance by it

In [145]:
mca = prince.MCA(n_components=len(active_crm), correction='benzecri', check_input=True, random_state=42)

mca_results = mca.fit(df_clean[active_crm])

The dimensionality reduction works well, but it's needed to deep dive in the results to see if the variables are well-represented

In [146]:
mca_results.eigenvalues_summary.loc[:10]

          eigenvalue % of variance % of variance (cumulative)
component
0              0.000        59.15%                     59.15%
1              0.000        12.62%                     71.77%
2              0.000         6.43%                     78.20%
3              0.000         3.11%                     81.31%
4              0.000         2.45%                     83.75%
5              0.000         2.41%                     86.16%
6              0.000         1.89%                     88.05%
7              0.000         1.61%                     89.67%
8              0.000         1.25%                     90.91%
9              0.000         1.01%                     91.92%
10             0.000         0.62%                     92.54%

Column contributions

In [147]:
mca.column_contributions_.head().style.format('{:.0}')

Checking the columns consines (>0.5 as parameter to well-represented column), parameters are far from being well-represented

In [148]:
column_cos2 = mca.column_cosine_similarities(df_clean[active_crm])

# cumulative representation
n_axis = 4
column_cos2_cumulative = column_cos2.iloc[:, :n_eixos].sum(axis=1)

# filtering 
well_represented_vars = column_cos2_acumulado[column_cos2_cumulative >= 0.5]

print(f"Total evaluated: {len(column_cos2_cumulative)}")
print(f"From {n_axis} axis (Cos2 >= 0.5): {len(well_represented_vars)}")

column_cos2_cumulative

Total evaluated: 1486
From 4 axis (Cos2 >= 0.5): 38

CRM_BUSINESS_LINE_ORIG_Mobile__0    0.013814
CRM_BUSINESS_LINE_ORIG_Mobile__1    0.013814
CRM_1519_PACK__0                    0.018537
CRM_1519_PACK__1                    0.018537
CRM_1521_PACK__0                    0.212096
                                      ...
CRM_2394_PACK__1                    0.013926
CRM_2395_PACK__0                    0.010553
CRM_2395_PACK__1                    0.010553
CRM_2397_PACK__0                    0.000098
CRM_2397_PACK__1                    0.000098
Length: 1486, dtype: float64

## TruncatedSVD

In [149]:
from sklearn.decomposition import TruncatedSVD

# TruncatedSVD mantendo 50 a 100 componentes
n_components = 100
svd = TruncatedSVD(n_components=n_components, random_state=42)
X_svd = svd.fit_transform(df_clean[active_crm])

print(f"Explained Variance: {svd.explained_variance_ratio_.sum()*100:.2f}% with {n_components} out of {len(active_crm)}")

Explained Variance: 77.15% with 100 out of 743